# @format

name: Reuse Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "The name of the artifact to download"
        required: false
        default: dist-files
        type: string
    # secrets:
    #   some-secret:
    #     required: false
    outputs:
      result:
        description: "The result of the deployment"
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    steps:
      - name: Get the code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Check the code
        run: ls

      - name: Deploy
        run: echo "Deploying"
      - name: Set the result
        id: deploy
        run: echo "step-result=success" >> $GITHUB_OUTPUT
